//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyStats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1939/01/07	BA	58	22	47	49	69
        ///1939/01/07	FI	27	57	81	43	61
        ///1939/01/07	MI	40	38	57	67	7
        ///1939/01/07	NA	85	44	48	88	55
        ///1939/01/07	PA	73	80	39	38	57
        ///1939/01/07	RM	73	24	4	39	22
        ///1939/01/07	TO	19	43	10	31	27
        ///1939/01/07	VE	9	43	61	14	75
        ///1939/01/14	BA	18	77	33	62	19
        ///1939/01/14	FI	31	47	12	7	80
        ///1939/01/14	MI	35	24	52	90	41
        ///1939/01/14	NA	4	10	36	63	35
        ///1939/01/14	PA	10	77	43	37	35
        ///1939/01/14	RM	4	86	61	84	58
        ///1939/01/14	TO	82	7	15	88	34
        ///1939/01/14	VE	85	21	45	65	56
        ///1939/01/21	BA	68	65	41	28	67
        ///1939/01/21	FI	37	82	69	9	6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string storico {
            get {
                return ResourceManager.GetString("storico", resourceCulture);
            }
        }
    }
}
